"""
Django settings for giftwiki project.
Generated by 'django-admin startproject' using Django 4.2.7.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Import database configuration for SQLite WAL mode (enables concurrent access)
try:
    from . import db_config
except ImportError:
    # db_config is optional - only needed for SQLite WAL mode
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY', 'django-insecure-k3as*djui($*yovvfforvv#8*ayh1!feuv)*i3$)_ka5k50lm-'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() in ('true', '1', 'yes')

# Allow Firebase Auth popups to communicate with the application
# Django 4.0+ defaults to 'same-origin' which blocks cross-origin popups
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
# Configure logging - only write to file in debug mode to reduce I/O overhead in production
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'gift': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO'),
            'propagate': False,
        },
        'boto3': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING' if not DEBUG else 'DEBUG'),
            'propagate': True,
        },
        'botocore': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'WARNING' if not DEBUG else 'DEBUG'),
            'propagate': True,
        },
    },
}

# Configure Cloud Logging in Production/Dev environment
if os.getenv('DJANGO_ENVIRONMENT') in ['prod', 'dev']:
    try:
        from google.cloud import logging as google_logging
        from google.cloud.logging.handlers import CloudLoggingHandler

        client = google_logging.Client()
        cloud_handler = CloudLoggingHandler(client)

        # Add cloud handler to root logger or specific loggers
        LOGGING['handlers']['cloud'] = {
            'class': 'google.cloud.logging.handlers.CloudLoggingHandler',
            'client': client,
        }

        # Update loggers to use cloud handler and console
        LOGGING['loggers']['django']['handlers'] = ['cloud', 'console']
        LOGGING['loggers']['gift'] = {  # App specific logger
            'handlers': ['cloud', 'console'],
            'level': 'INFO',
            'propagate': False,
        }
    except Exception as e:
        import sys

        print(f'Failed to setup Cloud Logging: {e}', file=sys.stderr)

# Only add file handler in debug mode
if DEBUG:
    LOGGING['handlers']['file'] = {
        'level': 'DEBUG',
        'class': 'logging.FileHandler',
        'filename': 'debug.log',
        'formatter': 'verbose',
    }
    LOGGING['loggers']['boto3']['handlers'].append('file')
    LOGGING['loggers']['botocore']['handlers'].append('file')


# Application definition
AUTH_USER_MODEL = 'gift.WikiUser'
ROOT_URLCONF = 'giftwiki.urls'
WSGI_APPLICATION = 'giftwiki.wsgi.application'
INTERNAL_IPS = ['127.0.0.1']
CORS_ALLOWED_ORIGINS = os.getenv('DJANGO_ALLOWED_ORIGINS', 'http://localhost').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('DJANGO_ALLOWED_ORIGINS', 'http://localhost').split(',')
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost').split(',')
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
# Redirect to Firebase auth page instead of Django login form
LOGIN_URL = '/auth.html'

# Feature Flags - Import from feature_flags module
try:
    from .feature_flags import STEWARD_PROXY_ENABLED
except ImportError:
    # Fallback for initial migration
    STEWARD_PROXY_ENABLED = False

INSTALLED_APPS = [
    'corsheaders',
    'storages',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'gift.apps.GiftConfig',
    'import_export',
]

# Only enable debug toolbar in development
if DEBUG:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'gift.middleware.error_logging.ErrorLoggingMiddleware',  # Log unhandled exceptions with request/trace context
    'gift.middleware.healthcheck.HealthCheckMiddleware',
    'gift.middleware.metrics.MetricsMiddleware',  # Handle /metrics endpoint early, before security checks
    'gift.middleware.prometheus.PrometheusMiddleware',  # Prometheus metrics - early in chain to track all requests
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',  # Must run before AuthenticationMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'gift.middleware.firebase_auth.FirebaseAuthMiddleware',  # Firebase auth - runs after AuthenticationMiddleware to fix session stripping issue
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Only enable debug toolbar middleware in development
if DEBUG:
    MIDDLEWARE.insert(2, 'debug_toolbar.middleware.DebugToolbarMiddleware')

# Authentication backends - add Firebase auth backend
AUTHENTICATION_BACKENDS = [
    'gift.middleware.firebase_auth.FirebaseAuthBackend',  # Firebase auth
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth (for admin, etc.)
]

# Firebase Client Configuration for Frontend
# Used to inject configuration into auth.html securely
FIREBASE_CLIENT_CONFIG = {
    'apiKey': os.environ.get('FIREBASE_API_KEY', ''),  # Must be set in environment
    'authDomain': os.environ.get('FIREBASE_AUTH_DOMAIN', 'wikileet.firebaseapp.com'),
    'projectId': os.environ.get('FIREBASE_PROJECT_ID', 'wikileet'),
    'storageBucket': os.environ.get('FIREBASE_STORAGE_BUCKET', 'wikileet.firebasestorage.app'),
    'appId': os.environ.get('FIREBASE_APP_ID', '1:179879905839:web:eeccfafc3a3fec117994da'),
    'measurementId': os.environ.get('GOOGLE_ANALYTICS_ID'),
}

# Google Analytics
GOOGLE_ANALYTICS_ID = os.environ.get('GOOGLE_ANALYTICS_ID')
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gift.context_processors.google_analytics',
                'giftwiki.feature_flags.get_context_processor',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Use PostgreSQL (Neon) if DJANGO_DB_HOST is set, otherwise fall back to SQLite
if os.getenv('DJANGO_DB_HOST'):
    # PostgreSQL/Neon configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DJANGO_DB_NAME', 'neondb'),
            'USER': os.getenv('DJANGO_DB_USER', 'neondb_owner'),
            'PASSWORD': os.getenv('DJANGO_DB_PASSWORD') or os.getenv('DJANGO_DB_PASS', ''),
            'HOST': os.getenv('DJANGO_DB_HOST'),
            'PORT': os.getenv('DJANGO_DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            },
            'CONN_MAX_AGE': int(
                os.getenv('DJANGO_DB_CONN_MAX_AGE', '0')
            ),  # 0 for serverless/Cloud Run to avoid closed connection errors
        }
    }
else:
    # SQLite configuration (fallback for local development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('DATABASE_PATH', os.path.join(BASE_DIR, 'db.sqlite3')),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
# Allow TIME_ZONE to be overridden by environment variable, but default to valid IANA timezone
TIME_ZONE = os.getenv(
    'DJANGO_TIME_ZONE', 'America/New_York'
)  # Changed from 'EST' - Django 5.1 requires IANA timezone names
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
USE_S3 = os.getenv('USE_S3') == 'TRUE'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Always use WhiteNoise to serve static files in production
# WhiteNoise serves static files directly from the application server (Gunicorn)
# This works well in Kubernetes and doesn't require S3 or a separate web server
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

if USE_S3:
    # AWS settings for media files (user uploads, profile pictures, etc.)
    # Note: Static files are served via WhiteNoise, not S3
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    # Use S3 for media files only
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
