apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: giftwiki
build:
  artifacts:
    - image: dukeman/gift-wiki
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - deploy
