# Generated by Django 5.1 on 2025-10-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Flag name (e.g., STEWARD_PROXY_ENABLED)', max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this feature is enabled')),
                ('description', models.TextField(blank=True, help_text='What this feature does')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
                'ordering': ['name'],
            },
        ),
    ]
