# Generated by Django 5.1 on 2025-12-07 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0002_featureflag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='gift.family'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('family', 'name')},
        ),
    ]
