# Generated by Django 5.1 on 2025-12-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_add_family_to_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_range',
            field=models.CharField(blank=True, choices=[('under_50', 'Under $50'), ('under_100', 'Under $100'), ('under_200', 'Under $200'), ('under_500', 'Under $500'), ('over_expectations', 'Over Expectations 😄')], help_text='Select a price range category', max_length=20, null=True),
        ),
    ]
