# Generated by Django 5.1 on 2025-12-07 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0005_add_profile_picture_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiuser',
            name='scraped_page_selected',
            field=models.BooleanField(default=False, help_text='Whether user has selected a scraped wiki page to import'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ScrapedWikiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(help_text='Original URL from the wiki')),
                ('scraped_at', models.DateTimeField(help_text='When this page was scraped')),
                ('item_count', models.IntegerField(default=0, help_text='Number of items on this page')),
                ('is_imported', models.BooleanField(default=False, help_text='Whether items have been imported by a user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, help_text='User who imported this page', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_scraped_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scraped Wiki Page',
                'verbose_name_plural': 'Scraped Wiki Pages',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedWikiItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Item description')),
                ('purchased', models.BooleanField(default=False, help_text='Whether item was marked as purchased in original wiki')),
                ('original_text', models.TextField(blank=True, help_text='Original text as scraped from wiki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scraped_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gift.scrapedwikipage')),
            ],
            options={
                'verbose_name': 'Scraped Wiki Item',
                'verbose_name_plural': 'Scraped Wiki Items',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='wikiuser',
            name='selected_scraped_page',
            field=models.ForeignKey(blank=True, help_text='The scraped wiki page this user selected to import', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='gift.scrapedwikipage'),
        ),
    ]
