# Generated by Django 5.1 on 2025-12-08 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0007_add_managers_to_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiuser',
            name='color_palette',
            field=models.CharField(choices=[('default', 'Default (Indigo/Purple)'), ('ocean', 'Ocean (Blue/Teal)'), ('forest', 'Forest (Green/Emerald)'), ('sunset', 'Sunset (Orange/Pink)'), ('midnight', 'Midnight (Dark Blue/Navy)'), ('rose', 'Rose (Pink/Rose)')], default='default', help_text='Color palette theme for the interface', max_length=20),
        ),
    ]
