# Generated by Django 5.1 on 2026-01-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0009_fix_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, help_text='Link to the product page', null=True),
        ),
    ]
