# Generated by Django 5.1 on 2026-03-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0010_item_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
