# Generated by Django 5.1 on 2026-07-14 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0011_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address allowed to log in', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allowed Email',
                'verbose_name_plural': 'Allowed Emails',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='LinkedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Secondary email address', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Linked Email',
                'verbose_name_plural': 'Linked Emails',
                'ordering': ['email'],
            },
        ),
    ]
