# Generated by Django 5.1 on 2026-07-14 17:12

import os
from django.db import migrations

def populate_allowed_emails(apps, schema_editor):
    AllowedEmail = apps.get_model('gift', 'AllowedEmail')
    allowed_users_env = os.getenv('DJANGO_ALLOWED_USERS', '').strip()
    if allowed_users_env:
        emails = {email.strip().lower() for email in allowed_users_env.split(',') if email.strip()}
        for email in emails:
            AllowedEmail.objects.get_or_create(email=email)

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0012_allowedemail_linkedemail'),
    ]

    operations = [
        migrations.RunPython(populate_allowed_emails, reverse_populate),
    ]
