# Generated by Django 5.1 on 2026-07-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0013_populate_allowed_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiuser',
            name='birthday',
            field=models.DateField(blank=True, help_text='Used for birthday-season grouping on home page', null=True),
        ),
    ]
