# Generated by Django 5.1 on 2026-07-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0014_wikiuser_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Summer'", max_length=50, unique=True)),
                ('start_month', models.IntegerField(help_text='Numeric month (1-12)')),
                ('end_month', models.IntegerField(help_text='Numeric month (1-12)')),
            ],
        ),
    ]
