# Generated by Django 5.1 on 2026-07-16 22:48

from django.db import migrations


def create_default_seasons(apps, schema_editor):
    Season = apps.get_model('gift', 'Season')
    # Default: Spring (Mar-May), Summer (Jun-Aug), Fall (Sep-Nov), Winter (Dec-Feb)
    seasons = [
        ('Spring', 3, 5),
        ('Summer', 6, 8),
        ('Fall', 9, 11),
        ('Winter', 12, 2),
    ]
    for name, start, end in seasons:
        Season.objects.get_or_create(name=name, defaults={'start_month': start, 'end_month': end})

class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0015_season'),
    ]

    operations = [
        migrations.RunPython(create_default_seasons, reverse_code=migrations.RunPython.noop),
    ]
