# Generated by Django 5.1 on 2026-07-16 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0016_populate_default_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikiuser',
            name='secret_santa_target',
            field=models.ForeignKey(blank=True, help_text='The person this user drew for the Christmas exchange.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secret_santa_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
