# Generated by Django 5.1 on 2026-07-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0017_wikiuser_secret_santa_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiuser',
            name='birthday',
            field=models.DateField(blank=True, help_text="User's birthday for organizing wishlists by season.", null=True),
        ),
    ]
