# Generated by Django 6.0.7 on 2026-07-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0018_alter_wikiuser_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='Mark as one of your most-wanted items'),
        ),
    ]
