# Generated by Django 6.0.7 on 2026-07-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0019_item_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the owner moved this received gift to their archive', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_sneaky',
            field=models.BooleanField(default=False, help_text='Surprise item added by someone else — hidden from the list owner'),
        ),
        migrations.AddField(
            model_name='item',
            name='thank_you_sent',
            field=models.BooleanField(default=False, help_text='Whether the owner sent a thank-you for this gift'),
        ),
    ]
