# Generated by Django 6.0.7 on 2026-07-27 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0020_item_archived_at_item_is_sneaky_item_thank_you_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangelogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(help_text='Plain text, one or two friendly sentences')),
                ('published_at', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('seen_by', models.ManyToManyField(blank=True, help_text='Users who have dismissed this entry', related_name='seen_changelog_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Changelog Entry',
                'verbose_name_plural': 'Changelog Entries',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
