# Generated by Django 6.0.7 on 2026-09-10 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_added_by(apps, schema_editor):
    """Seed added_by from updated_by for items that already exist.

    updated_by holds the creator until someone edits the item, so for existing
    rows it is the best available signal — and for sneaky items, which only a
    non-owner can create, it is almost certainly correct.
    """
    Item = apps.get_model('gift', 'Item')
    Item.objects.filter(added_by__isnull=True).update(added_by=models.F('updated_by'))


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0022_populate_changelog_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text='Who first added this item. Set once and never overwritten, unlike updated_by — attribution on a sneaky item is what stops two people buying the same idea.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_added_by, migrations.RunPython.noop),
    ]
