apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: gift-wiki

resources:
    - deployment.yaml
    - service.yaml
    - ingress.yaml

secretGenerator:
  - name: django-app-secrets
    envs:
      - .env