# Generated by Django 4.2.7 on 2023-11-30 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gift', '0003_item_is_deleted_item_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='steward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stewarded_wishlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
