#!/bin/bash
# Script to generate terraform.tfvars from deploy/dev/secrets.env
# This helps migrate from script-based secrets to Terraform

set -e

PROJECT_ID=$(gcloud config get-value project 2>/dev/null || echo "")
REGION="${REGION:-us-east1}"
SERVICE_NAME="${SERVICE_NAME:-giftwiki-dev}"

if [ -z "$PROJECT_ID" ]; then
    echo "Error: No GCP project configured. Run 'gcloud config set project PROJECT_ID'"
    exit 1
fi

SECRETS_FILE="deploy/dev/secrets.env"
TFVARS_FILE="terraform/terraform.tfvars"

if [ ! -f "$SECRETS_FILE" ]; then
    echo "Error: $SECRETS_FILE not found"
    exit 1
fi

echo "Generating terraform.tfvars from $SECRETS_FILE..."
echo ""

# Source the secrets file
source "$SECRETS_FILE"

# Create terraform.tfvars
cat > "$TFVARS_FILE" <<EOF
# Generated by scripts/generate-terraform-tfvars.sh
# DO NOT COMMIT THIS FILE - it contains sensitive values

project_id  = "$PROJECT_ID"
region      = "$REGION"
service_name = "$SERVICE_NAME"

secrets = {
  django-secret-key      = "$DJANGO_SECRET_KEY"
  django-db-user         = "$DJANGO_DB_USER"
  django-db-password     = "$DJANGO_DB_PASSWORD"
  aws-access-key-id      = "$AWS_ACCESS_KEY_ID"
  aws-secret-access-key  = "$AWS_SECRET_ACCESS_KEY"
}
EOF

echo "✅ Generated $TFVARS_FILE"
echo ""
echo "Next steps:"
echo "1. Review terraform/terraform.tfvars"
echo "2. Run: cd terraform && terraform init"
echo "3. Run: cd terraform && terraform plan"
echo "4. Run: cd terraform && terraform apply"
echo ""
echo "⚠️  Remember: terraform.tfvars is in .gitignore and should NOT be committed!"

