"""
Error logging middleware.

Catches unhandled exceptions, enriches them with request context and trace
information, and re-raises so Django's normal error handling continues.
"""

import logging
import traceback

logger = logging.getLogger(__name__)


def _get_trace_header(request):
    """Extract Cloud Run / Google Cloud trace context header if present."""
    return request.META.get('HTTP_X_CLOUD_TRACE_CONTEXT', '')


def _user_repr(user):
    if user is None:
        return 'anonymous'
    if hasattr(user, 'is_authenticated') and user.is_authenticated:
        return getattr(user, 'email', None) or getattr(user, 'username', None) or str(user)
    return 'anonymous'


class ErrorLoggingMiddleware:
    """
    Middleware that logs unhandled exceptions with rich request context.

    This should be placed early in MIDDLEWARE so it wraps the rest of the
    stack and can capture errors raised by other middleware or views.
    """

    def __init__(self, get_response):
        self.get_response = get_response

    def __call__(self, request):
        # Marker used to avoid logging both the exception and the eventual
        # 500 response generated by Django's exception handler.
        request._error_logged = False

        try:
            response = self.get_response(request)
        except Exception as exc:  # noqa: BLE001 - intentionally broad to log any unhandled error
            self._log_exception(request, exc)
            raise

        # Log explicit 500 responses returned by upstream middleware/views,
        # but only if we did not already log an exception for this request.
        if response.status_code >= 500 and not getattr(request, '_error_logged', False):
            self._log_server_error(request, response)

        return response

    def _log_exception(self, request, exc):
        request._error_logged = True
        trace_header = _get_trace_header(request)
        user = _user_repr(getattr(request, 'user', None))

        logger.error(
            'Unhandled exception in request: %s %s - %s: %s',
            request.method,
            request.path,
            type(exc).__name__,
            str(exc),
            extra={
                'request_method': request.method,
                'request_path': request.path,
                'request_user': user,
                'trace_header': trace_header,
                'exception_type': type(exc).__name__,
                'exception_message': str(exc),
                'traceback': traceback.format_exc(),
            },
            exc_info=True,
        )

    def _log_server_error(self, request, response):
        trace_header = _get_trace_header(request)
        user = _user_repr(getattr(request, 'user', None))

        logger.error(
            'Server error response: %s %s returned status %s',
            request.method,
            request.path,
            response.status_code,
            extra={
                'request_method': request.method,
                'request_path': request.path,
                'request_user': user,
                'trace_header': trace_header,
                'status_code': response.status_code,
            },
        )
