# Generated by Django 6.1.1 on 2026-09-24 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_user_monthly_messages', models.PositiveIntegerField(default=200, help_text='Messages one person may send per month')),
                ('global_monthly_messages', models.PositiveIntegerField(default=1000, help_text='Messages the whole family may send per month')),
                ('model_name', models.CharField(default='gemini-2.5-flash', help_text='Vertex AI model id. Verify against current Vertex docs before changing.', max_length=100)),
                ('enabled_until', models.DateField(blank=True, help_text='After this date the assistant hides itself. Blank means no end date.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Assistant Settings',
                'verbose_name_plural': 'Assistant Settings',
            },
        ),
        migrations.CreateModel(
            name='AssistantUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text="Month key, e.g. '2026-09'", max_length=7)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Usage',
                'verbose_name_plural': 'Assistant Usage',
                'ordering': ['-period', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'period'), name='unique_usage_per_user_period')],
            },
        ),
    ]
