# Generated by Django 6.1.1 on 2026-09-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EasterEggFind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='easter_eggs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Easter Egg Find',
                'verbose_name_plural': 'Easter Egg Finds',
                'ordering': ['found_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'slug'), name='unique_egg_per_user')],
            },
        ),
    ]
