# Generated by Django 6.1.1 on 2026-09-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_eastereggfind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='model_name',
            field=models.CharField(default='gemini-3.8-flash', help_text='Vertex AI model id. Confirm against the live publisher list rather than memory: curl the aiplatform publishers/google/models endpoint with an access token and an x-goog-user-project header, and pick a GA Flash model.', max_length=100),
        ),
    ]
